In [14]:
import pandas as  pd
import matplotlib as mpl
import numpy as np
import seaborn as sns

In [18]:
train = pd.read_csv("training.csv",sep=';')
test = pd.read_csv("validation.csv",sep=';')
    
train.head(10)
train.head(10)

,variable1,variable2,variable3,variable4,variable5,variable6,variable7,variable8,variable9,variable10,variable11,variable12,variable13,variable14,variable15,variable17,variable18,variable19,classLabel
0,a,"17,92","5,4e-05",u,g,c,v,"1,75",f,t,1,t,g,80.0,5,800000.0,t,0,no.
1,b,"16,92","3,35e-05",y,p,k,v,"0,29",f,f,0,f,s,200.0,0,2000000.0,NaN,0,no.
2,b,"31,25","0,0001125",u,g,ff,ff,0,f,t,1,f,g,96.0,19,960000.0,t,0,no.
3,a,"48,17","0,0001335",u,g,i,o,"0,335",f,f,0,f,g,0.0,120,0.0,NaN,0,no.
4,b,"32,33","0,00035",u,g,k,v,"0,5",f,f,0,t,g,232.0,0,2320000.0,f,0,no.
5,a,"34,83","0,000125",y,p,i,h,"0,5",f,f,0,t,g,160.0,0,1600000.0,f,0,no.
6,a,"26,17",2e-04,u,g,j,j,0,f,f,0,t,g,276.0,1,2760000.0,NaN,0,no.
7,b,"21,17","8,75e-05",y,p,c,h,"0,25",f,f,0,f,g,280.0,204,2800000.0,NaN,0,no.
8,b,"28,92","3,75e-05",u,g,c,v,"0,29",f,f,0,f,g,220.0,140,2200000.0,NaN,0,no.
9,b,"18,17","0,001025",u,g,c,h,"1,085",f,f,0,f,g,320.0,13,3200000.0,NaN,0,no.

# ********** ******** ************** **************
# Preprocessing
# ********** ******** ************** **************

In [3]:
###### see basics about the data
train.describe()

        variable11   variable14     variable15    variable17   variable19
count  3700.000000  3600.000000    3700.000000  3.600000e+03  3700.000000
mean      4.160000   162.695000    2246.705946  1.626950e+06     0.925405
std       6.750553   156.045682    8708.571126  1.560457e+06     0.262772
min       0.000000     0.000000       0.000000  0.000000e+00     0.000000
25%       0.000000     0.000000       0.000000  0.000000e+00     1.000000
50%       2.000000   120.000000     113.000000  1.200000e+06     1.000000
75%       6.000000   280.000000    1059.750000  2.800000e+06     1.000000
max      67.000000  1160.000000  100000.000000  1.160000e+07     1.000000

In [4]:
print("total number of rows")
print(train.shape[0])
print("number of rows have  null values ")
print(train.shape[0]-(train.dropna(how="any")).shape[0])

# number of null rows is large so we can't simply delete these rows

total number of rows
3700
number of rows have  null values
2237

In [5]:
# number of rows that is all its values are null
print ("total number of rows")
print(test.shape[0])
print ("number of null rows ")
print(test.shape[0]-(test.dropna(how="any")).shape[0])

total number of rows
200
number of null rows
116

In [6]:

# see which columns have missing values

train.isnull().sum()

variable1       39
variable2       39
variable3        0
variable4       64
variable5       64
variable6       66
variable7       66
variable8        0
variable9        0
variable10       0
variable11       0
variable12       0
variable13       0
variable14     100
variable15       0
variable17     100
variable18    2145
variable19       0
classLabel       0
dtype: int64

In [7]:
test.isnull().sum()

variable1       3
variable2       3
variable3       0
variable4       2
variable5       2
variable6       3
variable7       3
variable8       0
variable9       0
variable10      0
variable11      0
variable12      0
variable13      0
variable14      3
variable15      0
variable17      3
variable18    111
variable19      0
classLabel      0
dtype: int64

 we see that all columns have few null of nulls except variable18 (null ratio more than 50%)

- so i will handle variable 18 later but now other variables will be imputed (numeric values with mean() , string values with mode())

In [8]:
modes=["variable1","variable2","variable4","variable5","variable6","variable7"]
for col in modes:
    train[col].fillna(train[col].mode()[0],inplace=True)
    test[col].fillna(test[col].mode()[0],inplace=True)
    
modes=["variable14","variable17"]
for col in modes:
    train[col].fillna(train[col].mean(),inplace=True)
    test[col].fillna(test[col].mean(),inplace=True)
    


train.isnull().sum()

variable1        0
variable2        0
variable3        0
variable4        0
variable5        0
variable6        0
variable7        0
variable8        0
variable9        0
variable10       0
variable11       0
variable12       0
variable13       0
variable14       0
variable15       0
variable17       0
variable18    2145
variable19       0
classLabel       0
dtype: int64

### Now see correlaion between columns

In [9]:


corr=train.apply(lambda x: x.factorize()[0]).corr()
corr

,variable1,variable2,variable3,variable4,variable5,variable6,variable7,variable8,variable9,variable10,variable11,variable12,variable13,variable14,variable15,variable17,variable18,variable19,classLabel
variable1,1.000000,0.057298,-0.001978,0.044526,0.044526,-0.059088,0.050991,0.116893,-0.056598,0.073279,-0.029171,-0.135270,0.005259,0.168331,-0.019284,0.168331,0.012780,-0.035487,-0.035487
variable2,0.057298,1.000000,0.272006,-0.036504,-0.036504,-0.038272,-0.015443,0.093351,0.017492,-0.091852,0.099087,0.010002,0.041131,0.147145,0.142482,0.147145,0.005602,0.055939,0.055939
variable3,-0.001978,0.272006,1.000000,-0.073800,-0.073800,0.072217,-0.013799,0.146094,0.059148,-0.109798,0.188087,0.039457,-0.015757,0.032371,0.174686,0.032371,-0.015036,0.069974,0.069974
variable4,0.044526,-0.036504,-0.073800,1.000000,1.000000,-0.008422,-0.034440,-0.171110,-0.214103,0.166765,-0.104309,-0.171140,0.144363,0.042860,-0.086077,0.042860,0.116571,-0.102442,-0.102442
variable5,0.044526,-0.036504,-0.073800,1.000000,1.000000,-0.008422,-0.034440,-0.171110,-0.214103,0.166765,-0.104309,-0.171140,0.144363,0.042860,-0.086077,0.042860,0.116571,-0.102442,-0.102442
variable6,-0.059088,-0.038272,0.072217,-0.008422,-0.008422,1.000000,0.035999,0.177944,0.140957,-0.051057,0.003959,-0.081705,-0.173708,0.142643,0.000855,0.142643,0.009578,0.080151,0.080151
variable7,0.050991,-0.015443,-0.013799,-0.034440,-0.034440,0.035999,1.000000,0.093523,0.050948,-0.008675,0.109298,0.030605,-0.078400,0.016457,-0.080752,0.016457,-0.022485,0.047570,0.047570
variable8,0.116893,0.093351,0.146094,-0.171110,-0.171110,0.177944,0.093523,1.000000,0.241325,-0.209740,0.225857,-0.021079,-0.133712,0.140333,0.143299,0.140333,0.004149,0.158145,0.158145
variable9,-0.056598,0.017492,0.059148,-0.214103,-0.214103,0.140957,0.050948,0.241325,1.000000,-0.399801,0.275668,-0.063239,-0.392016,-0.004386,0.142053,-0.004386,-0.108476,0.545244,0.545244
variable10,0.073279,-0.091852,-0.109798,0.166765,0.166765,-0.051057,-0.008675,-0.209740,-0.399801,1.000000,-0.551843,0.010270,0.300049,-0.012774,-0.334691,-0.012774,0.181617,-0.218894,-0.218894
variable11,-0.029171,0.099087,0.188087,-0.104309,-0.104309,0.003959,0.109298,0.225857,0.275668,-0.551843,1.000000,0.022397,-0.162470,0.026454,0.323951,0.026454,-0.038178,0.178090,0.178090
variable12,-0.135270,0.010002,0.039457,-0.171140,-0.171140,-0.081705,0.030605,-0.021079,-0.063239,0.010270,0.022397,1.000000,0.113403,-0.186069,0.090432,-0.186069,0.015376,-0.042168,-0.042168
variable13,0.005259,0.041131,-0.015757,0.144363,0.144363,-0.173708,-0.078400,-0.133712,-0.392016,0.300049,-0.162470,0.113403,1.000000,-0.019330,-0.200016,-0.019330,0.089426,-0.013762,-0.013762
variable14,0.168331,0.147145,0.032371,0.042860,0.042860,0.142643,0.016457,0.140333,-0.004386,-0.012774,0.026454,-0.186069,-0.019330,1.000000,0.074055,1.000000,-0.021983,0.030069,0.030069
variable15,-0.019284,0.142482,0.174686,-0.086077,-0.086077,0.000855,-0.080752,0.143299,0.142053,-0.334691,0.323951,0.090432,-0.200016,0.074055,1.000000,0.074055,-0.064756,0.079569,0.079569
variable17,0.168331,0.147145,0.032371,0.042860,0.042860,0.142643,0.016457,0.140333,-0.004386,-0.012774,0.026454,-0.186069,-0.019330,1.000000,0.074055,1.000000,-0.021983,0.030069,0.030069
variable18,0.012780,0.005602,-0.015036,0.116571,0.116571,0.009578,-0.022485,0.004149,-0.108476,0.181617,-0.038178,0.015376,0.089426,-0.021983,-0.064756,-0.021983,1.000000,-0.106082,-0.106082
variable19,-0.035487,0.055939,0.069974,-0.102442,-0.102442,0.080151,0.047570,0.158145,0.545244,-0.218894,0.178090,-0.042168,-0.013762,0.030069,0.079569,0.030069,-0.106082,1.000000,1.000000
classLabel,-0.035487,0.055939,0.069974,-0.102442,-0.102442,0.080151,0.047570,0.158145,0.545244,-0.218894,0.178090,-0.042168,-0.013762,0.030069,0.079569,0.030069,-0.106082,1.000000,1.000000

In [10]:
corr=test.apply(lambda x: x.factorize()[0]).corr()
corr

,variable1,variable2,variable3,variable4,variable5,variable6,variable7,variable8,variable9,variable10,variable11,variable12,variable13,variable14,variable15,variable17,variable18,variable19,classLabel
variable1,1.000000e+00,-0.014545,0.093426,-0.070427,-0.070427,0.062747,0.160550,0.093942,-0.018021,0.069544,0.081673,1.483598e-17,0.126668,-0.097159,0.024974,-0.097159,0.064157,-0.066815,-0.067873
variable2,-1.454530e-02,1.000000,0.356811,-0.103339,-0.103339,0.112411,0.067394,0.371886,-0.132856,0.113717,0.187633,2.979469e-02,0.074999,0.448703,0.413836,0.448703,0.071359,-0.027394,0.215335
variable3,9.342599e-02,0.356811,1.000000,-0.004177,-0.004177,0.170251,0.254666,0.405679,-0.150950,0.143580,0.180989,-2.049228e-02,0.047674,0.187193,0.200487,0.187193,0.093758,-0.043957,0.214476
variable4,-7.042667e-02,-0.103339,-0.004177,1.000000,1.000000,0.035031,-0.013618,-0.160119,0.098184,-0.128449,-0.106321,1.046299e-01,-0.003040,-0.117275,-0.136625,-0.117275,0.002184,-0.127881,-0.158147
variable5,-7.042667e-02,-0.103339,-0.004177,1.000000,1.000000,0.035031,-0.013618,-0.160119,0.098184,-0.128449,-0.106321,1.046299e-01,-0.003040,-0.117275,-0.136625,-0.117275,0.002184,-0.127881,-0.158147
variable6,6.274691e-02,0.112411,0.170251,0.035031,0.035031,1.000000,0.179394,0.013294,-0.113035,0.117786,0.173325,1.420025e-02,0.096357,0.059191,0.070445,0.059191,0.090170,-0.045441,0.178708
variable7,1.605498e-01,0.067394,0.254666,-0.013618,-0.013618,0.179394,1.000000,0.186284,-0.175899,0.216433,0.209348,9.731705e-02,0.047125,-0.002740,0.099188,-0.002740,0.048528,-0.183821,0.295379
variable8,9.394202e-02,0.371886,0.405679,-0.160119,-0.160119,0.013294,0.186284,1.000000,-0.347467,0.249841,0.282955,-6.275823e-02,0.051231,0.202800,0.271546,0.202800,0.086131,0.005274,0.294410
variable9,-1.802131e-02,-0.132856,-0.150950,0.098184,0.098184,-0.113035,-0.175899,-0.347467,1.000000,-0.522323,-0.452192,1.011443e-02,-0.039672,-0.165020,-0.180424,-0.165020,-0.142513,-0.030343,-0.720398
variable10,6.954358e-02,0.113717,0.143580,-0.128449,-0.128449,0.117786,0.216433,0.249841,-0.522323,1.000000,0.708750,8.006408e-02,0.218518,0.098330,0.358386,0.098330,0.245677,0.040032,0.569050
variable11,8.167319e-02,0.187633,0.180989,-0.106321,-0.106321,0.173325,0.209348,0.282955,-0.452192,0.708750,1.000000,7.967375e-02,0.174587,0.159201,0.377483,0.159201,0.156134,-0.056303,0.528066
variable12,1.483598e-17,0.029795,-0.020492,0.104630,0.104630,0.014200,0.097317,-0.062758,0.010114,0.080064,0.079674,1.000000e+00,0.130744,-0.099983,0.135207,-0.099983,-0.037573,-0.020000,0.090221
variable13,1.266678e-01,0.074999,0.047674,-0.003040,-0.003040,0.096357,0.047125,0.051231,-0.039672,0.218518,0.174587,1.307441e-01,1.000000,0.005994,0.212601,0.005994,0.110531,0.032686,0.079950
variable14,-9.715858e-02,0.448703,0.187193,-0.117275,-0.117275,0.059191,-0.002740,0.202800,-0.165020,0.098330,0.159201,-9.998340e-02,0.005994,1.000000,0.185042,1.000000,0.023429,0.184762,0.181715
variable15,2.497365e-02,0.413836,0.200487,-0.136625,-0.136625,0.070445,0.099188,0.271546,-0.180424,0.358386,0.377483,1.352067e-01,0.212601,0.185042,1.000000,0.185042,0.157034,-0.041824,0.298855
variable17,-9.715858e-02,0.448703,0.187193,-0.117275,-0.117275,0.059191,-0.002740,0.202800,-0.165020,0.098330,0.159201,-9.998340e-02,0.005994,1.000000,0.185042,1.000000,0.023429,0.184762,0.181715
variable18,6.415677e-02,0.071359,0.093758,0.002184,0.002184,0.090170,0.048528,0.086131,-0.142513,0.245677,0.156134,-3.757346e-02,0.110531,0.023429,0.157034,0.023429,1.000000,-0.087671,0.044571
variable19,-6.681531e-02,-0.027394,-0.043957,-0.127881,-0.127881,-0.045441,-0.183821,0.005274,-0.030343,0.040032,-0.056303,-2.000000e-02,0.032686,0.184762,-0.041824,0.184762,-0.087671,1.000000,0.010025
classLabel,-6.787267e-02,0.215335,0.214476,-0.158147,-0.158147,0.178708,0.295379,0.294410,-0.720398,0.569050,0.528066,9.022131e-02,0.079950,0.181715,0.298855,0.181715,0.044571,0.010025,1.000000

### From correlation analysic

-  we recognize (variable4 and varaible5) are totally correlated in both test and train data set
-  we recognize (varaible17 and varaible14) are totally correlated in both test and train data set
<br>
so we will remove variable 5  and varaible17

----------------------------------------
# Modification 1
-  we recognize (varaible18) has a weak correlaction with label and also has many Nan Values (more than 50%) and also i don't have other information to decide if this data is important or not
<br>
so we will remove variable18

# Modification 2 oversampling the data unblanced
-----------------------------------------

-  we recognize classLabel and varaible19 are totally correlated in trian but not in test so there is something wrong and can affect classificatio learning

In [11]:
columns = ["variable5","variable17","variable18"]
train.drop(columns, axis=1, inplace=True)
test.drop(columns, axis=1, inplace=True)

In [20]:

train["variable3"].unique()

array(['5,4e-05', '3,35e-05', '0,0001125', '0,0001335', '0,00035',
       '0,000125', '2e-04', '8,75e-05', '3,75e-05', '0,001025',
       '0,0013665', '3e-04', '0,001', '0,000204', '0,0014585', '0,00155',
       '0,000325', '0,000275', '0,0002335', '5e-05', '0,0008125',
       '0,00165', '0,00025', '0,0004585', '0,0001375', '5e-04', '7,5e-05',
       '0,00015', '0,000221', '8,35e-05', '0,00085', '0,000104',
       '0,000175', '0,000425', '1,65e-05', '0,0016', '0,001075',
       '0,000304', '0,000154', '0,0004915', '0,0015', '0,00055',
       '0,0009625', '2,9e-05', '1e-04', '0,000254', '0,0009415', '4e-04',
       '0,00065', '6,7e-05', '7e-04', '0,0003165', '6e-04', '0,0001835',
       '7,9e-05', '0,0005085', '0,0026335', '0,00115', '0,001021',
       '0,0001165', '0,0001085', '0,0003125', '4,15e-05', '0,00045',
       '0,0005835', '0,0013', '0,000171', '0,000354', '5,85e-05', '0',
       '0,0006665', '8,3e-05', '0,0004625', '0,000925', '6,65e-05',
       '0,00125', '0,00105', '0,0011', '0,0005125', '0,0004415',
       '0,000846', '0,002521', '0,0010915', '4,6e-05', '9e-04',
       '0,0002835', '0,0002085', '0,00135', '0,0004085', '0,0002415',
       '0,0019', '0,000108', '0,0010085', '0,000975', '0,00095', '0,0022',
       '0,000271', '0,001775', '0,001175', '0,0011625', '0,000504',
       '0,000525', '8e-04', '0,0008585', '0,000621', '9,15e-05',
       '0,0007585', '0,000121', '5,8e-05', '0,000225', '1,7e-05',
       '0,000725', '0,000375', '0,000571', '6,25e-05', '0,000229',
       '0,0006165', '0,000446', '0,0009335', '2,05e-05', '0,0002875',
       '0,001275', '1,25e-05', '0,0005625', '0,001254', '2,5e-05',
       '0,0001665', '0,0002165', '0,0002665', '0,0003375', '0,000529',
       '0,001146', '0,000954', '0,0007625', '0,001029', '0,0010125',
       '0,000404', '0,0014', '0,0013585', '0,001225', '0,0021', '0,0012',
       '0,0005665', '0,002', '0,00195', '0,0028', '4e-06', '7,05e-05',
       '0,00145', '0,001375', '2,1e-05', '0,000146', '0,000479',
       '0,0005875', '0,0011125', '0,00185', '0,000704', '0,001125',
       '0,000675', '7,1e-05', '0,0018125', '0,0007835', '0,0001585',
       '0,000471', '0,0012835', '0,0004125', '0,000329', '0,0011585',
       '0,000996', '0,001479', '0,0016165', '0,0025125', '0,0010335',
       '0,001233', '0,00075', '0,000917', '0,0011045', '0,000708',
       '0,0012125'], dtype=object)

# ********** ******** ************** **************
# Learning
# ********** ******** ************** **************

In [ ]:
"""
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

categorical_feature_mask = train.dtypes==object


categorical_cols = train.columns[categorical_feature_mask].tolist()

print(categorical_cols, train.dtypes)

le = LabelEncoder()
train[categorical_cols] = train[categorical_cols].apply(lambda col: le.fit_transform(col))

train.head()
"""

In [ ]:
"""
x_train=train.drop("classLabel",axis=1)
y_train=train["classLabel"]

x_test=test.drop("classLabel",axis=1)
y_test=test["classLabel"]

logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)
"""